version: "3.3"
services:
  bot:
    container_name: trade-ws-client
    image: trade-ws-client
    build: .
    env_file: .env
    ports:
      - "8985:8985"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "2048M"
        reservations:
          cpus: "0.25"
          memory: "128M"
