name: "Build Demo"

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    name: Maven Test
    runs-on: [x64, linux]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test WS Server
        run: |
          mvn test

  deploy:
    name: Deploy
    needs: test
    runs-on: [x64, linux]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy container
        run: |
          echo "Deploy container"
          docker-compose down
          docker-compose rm -v
          docker system prune -a
          docker-compose build --no-cache
          docker-compose up -d
